language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER invoicify WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: 1Lbpp5R+cOb6SJ3o4vwZETnOkzzXlzpA1U79qoV43Wv2gnfT28P8RUcwcZ9az39ogeOAck8oinhs4boaCQ3o7FHPGkzYgaLhvpUeRArMyUpUwOklm7G/XGZ3VxgtYtpfVp1JzEFfD+b53Cmx/g5ozCStCxNaPoQR08E93KbKgNIPtTsIIo9k7ZgwpBrNFynZHsF6P7Ku0VSXr7og7X5u0ct8r5ZTsFuy7Kpvj75Gy9/bRknRYGJBMOqazIJoDdzLdrE4HwCgvqSr2LmZifH89fTb6q5OKcMdKw3yEm+d/XprBvEnukEQFckN45C7/T/678493g1AAOD9TvmXWeapU2+xMc7MlZTDE0PT4pywDfQCUvgGl42mhtzJGZqzlf+3byYrDaUKjRVBf89smhbG0stJRWyRWlAgS+FxTssEZXe5L+CQo2+/++NyiZ4AkBsEYfmO6q5JF/cFIiXHY4GbgZZClf9McRaIY+tVMKlJ/h1v3mzlhRN0dViz9wW1LglaYabGk4S3Wzg0GdQVUTlgtTL2EwDdQ7achlSwdKAeA+TBBUzOAAPEis/zyjbEWwDRVhH8cxp1Ghc3ukksKSr40BJl7n8jdhJ/rwu4YEkeO+SCGvFAZSKtPKIB6V0UNEWEmXpPeVApRtIfuTLV0XetBbsL8c/RBTlKxR5DZgWVKEQ=
  app: frozen-journey-75595
