language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER invoicify WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: fZKluIc4y4Tnuw9fVUd4NGsq7J46Qprh1nElA7apsxREmVxE3yNRoeACT0kWg/SaVJqP5Ut+IO/X9CiFfmcHw+w9pRiyjGR14O4QOKRBPzP/bOGD1gaKgNVj1dg5QZLkbL4yl9UnIGXNngYA11vdiALNJlGdj8L0UrnkQ5izRHkiPdCCPLH/DSeFPPLSrJq9fQ8e8cnyk+xJCPhT07CcvVZE+2IoV2vvmsA2tnFeQg7IwWgwXdIGnWwW7ufqxZbKu/xP4gljV9NfssfCWafrqpwCPNCWGuhvCI9+PKFmBg6ZjPZzflSV/wOlPEiNmFh1+toWdEXdY0Z2S46q2FADPL95gyZP3atpr8FgCwRk3YekksCzlcUWKDSnEwc0lrBAb06MEmX4a+eLKKUsq8M4FuSzYkt0XuY9FaKeAf/P9cYt3buc5qFHeFXgx0S+hUDFIjXqQY2rwV0pKtkQ0QqmCchCvDaRpoEMpXYoc+9ZDMKEX4II0gYkm7s3RkmFlB+TAgxpNEML5jD4E+/bgNefPRFKP5psgZWtqEDWwyW3SHiXOR0884JWS92jxwjrsvJ1H1zDMwAGnA821n7kJmkZ1ap1wNzibsRbeoFBQgvCgJ5Xs361dm9VfF5sP2iCpHFzVHqZn7WDI1LLBftKgVFRLud78ZCe7oGAGTjsP5OEDqQ=
